name: Notify Deployment Repository on Merge

on:
  push:
    branches:
      - main
      - stage
      - testing

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Deployment Repository
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "Triggering deployment for branch: $BRANCH_NAME"
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/mjsol12/Testing-CI-CD/dispatches \
        -d "{\"event_type\": \"trigger-sync\", \"client_payload\": {\"branch\": \"$BRANCH_NAME\"}}"
